### ISSUE TITLE
Add isomorphic fetch dependency

### ISSUE THREAD

**Issue by buesing** [madebywild/wild-next#12]
Out of the box the error 'fetch is not defined' shows up when trying to fetch something.
Solution: add npm repo `isomorphic-unfetch` and `import fetch from 'isomorphic-unfetch';`

**Comment by tom2strobl** [comment]
That's the easy solution, I'm curious if  we should go for something that does not need to be imported like a babel plugin or https://gist.github.com/Couto/b29676dd1ab8714a818f
