### ISSUE TITLE
env.config.js not exporting correct NODE_ENV

### ISSUE THREAD

**Issue by FrencisAlreadyInUse** [madebywild/wild-next#15]
**issue**
the following export script in _package.json_ `"export": "NODE_ENV=staging next build && next export -o dist",` will always export the production environment

Only the `NODE_ENV=development` works fine

*current dirty fix*
placing the staging url inside the production's PUBLIC_URL

**Comment by buesing** [comment]
Fix is to use the new `WILD_ENV`. `NODE_ENV` can only be set to production or development.
