### ISSUE TITLE
Invalid Configuration Object: Webpack

### ISSUE THREAD

**Issue by abhinayar** [madebywild/wild-next#16]
Getting this error when I try to start the dev server:

**(node:1832) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): 
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.

 - configuration[0] should be an object.
 - configuration[1] should be an object.

(node:1832) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.**

Looking further into it and will post a fix but this is without editing a single file. Thought I would let you guys know.

Cheers.

**Comment by buesing** [comment]
Should be fixed with c4dc4dd3456ff3d6e1eca722feecd56ae73ce98a. Feel free to reopen if you still get it.
