### ISSUE TITLE
REMINDER: remove styles from _document for next version bump

### ISSUE THREAD

**Issue by FrencisAlreadyInUse** [madebywild/wild-next#21]
If we're going to bump next' version.
Make sure to delete styles `<link rel="stylesheet" href="/_next/static/style.css" />`.

https://github.com/zeit/next-plugins/pull/228
*Next.js now knows how to handle .css chunks attached to pages*

**Comment by FrencisAlreadyInUse** [comment]
https://github.com/zeit/next-plugins/issues/196#issuecomment-399679452

**Comment by buesing** [comment]
Already removed.
