### ISSUE TITLE
Root level .scss files being cached + no hot updates

### ISSUE THREAD

**Issue by abhinayar** [madebywild/wild-next#24]
Hey guys, 

It seems the root level .scss files are being compiled and cached somewhere and don't hot update for me. For example:

The ```vars.scss``` file in the root level of this boilerplate can be easily accessed by all other .scss files, however when a variable there is updated it doesn't seem to update in those files.

Have not been able to narrow down the problem, but it could have something to do with the ./sass-cache folder, etc. but because of the nextjs + Webpack obfuscation of normal sass/compass activities it's hard for me to tell.

Any ideas?

**To Replicate**
```
1. Clone Repo
2. Edit vars.scss
3. Reference vars.scss in a component scss file
4. Edit the vars.scss value
5. Refresh/hard-refresh page, restart server, etc. etc.
```

The component scss file will not change.

Only fix to date was deleting and re-installing /node_modules/, which leads me to believe there might be some cache-issues going on.

Thanks,
Abhi

**Comment by buesing** [comment]
Fixed by https://github.com/madebywild/wild-next/pull/25
