### ISSUE TITLE
Global variables 

### ISSUE THREAD

**Issue by adamjw3** [madebywild/wild-next#26]
Do you hand to import vars.scss in every component file? Anyway of being able to just include it in global?

**Comment by buesing** [comment]
@adamjw3 AFAIK there's no way of automatically importing sass variables. Also I think it's not a bad idea to be explicit about it.

**Comment by buesing** [comment]
Then again, I just merged https://github.com/madebywild/wild-next/pull/25 which also solves your issue I think 😅
