### ISSUE TITLE
Switch to a library that provides utility effects (such as useClipBoard, useClickOutside, useScroll, etc.)

### ISSUE THREAD

**Issue by claudiopedrom** [madebywild/wild-next#33]
As suggested by @r0skar, discuss if it makes sense to add to the boilerplate a package like [react-use](https://github.com/streamich/react-use).

**Some opinions:**
> The only issue I see with this type of libraries, is that they add a lot of features/code that you will never use (90%). And most of the things you can simply create/isolate on your project.

> I like the idea of a single utility library (same for Lodash, rather than separate packages), and I would hope the bundler would use tree shaking to make sure there’s nothing unnecessarily included.

> But I see the advantages of having isolated hooks (less deps, less mental overhead, can be modified easily…). My worry is that going forward we will run into a situation where we re-created most of the library’s hooks, but we have to maintain them ourselves across different projects.

**Comment by edoardolunardi** [comment]
@claudiopedrom I do agree. I would rather include those 5-6 custom utilities/hooks we usually use, written by us and already tested.

**Comment by r0skar** [comment]
> already tested.

Are they, though? Imo one of the biggest advantages of using a popular library is that it is battle-tested and being used in production by thousand of sites.

Our custom hooks are not tested for every edge case and if we discover an issue we would need to go back to all projects and update the hooks one by one (and lets be honest: no1 is going to do that).

**Comment by edoardolunardi** [comment]
Yeah that might be true.

**Comment by bs1180** [comment]
I support using external libs over writing something ourselves - it doesn't necessarily need to get added to the boilerplate though, I guess?

**Comment by r0skar** [comment]
I agree that adding it to the boilerplate is not the best of ideas. Lets keep it lean and simple and add a reference to `react-use` in the upcoming [Documentation](https://github.com/madebywild/wild-next/issues/40).
