### ISSUE TITLE
Path aliases

### ISSUE THREAD

**Issue by r0skar** [madebywild/wild-next#34]
At the moment, we are using ts to define path aliases for all kind of folders

https://github.com/madebywild/wild-next/blob/f324ab86aff196a28ca674c31dc88956a1478e96/tsconfig.json#L17-L28

- Do we want to keep using this approach at all or should we stick to relative imports?
- Should we change the `@` prefix, since it kinda conflicts with org packages which also usually are prefixed with `@`?
Maybe use `~`?

**Comment by edoardolunardi** [comment]
I personally hate to import stuff like `import SomeComponent from "../../../../../../../../../../something"`, so I would stick with that.
Why don't we simply keep `root` instead of `@root` ?

**Comment by r0skar** [comment]
Yeah we could get rid of the prefix altogether, and I kinda like that approach. But it comes with its own caveats. Lets say you want to import `styles/index.ts`, the import would look like: `import * from "styles"`, which looks like its an npm package.

This might not be a big issue at the beginning, but can lead to confusion, because you can never be sure if an import is a npm package or just a path.

What I also like: we could map `~` to the `src` dir. This would allow for imports such as `import * from "~/styles"`, which looks and behaves a lot like the bash tilde shell expansion, where it maps `~` to `$HOME` (and `src` is kinda the project's home anway).

**Comment by edoardolunardi** [comment]
Yeah correct, well, when in doubt I always check if what's imported is present in `package.json` to be sure wether it's a npm package or not.

We can use `~` then

**Comment by r0skar** [comment]
I suggest we create two aliases that kinda resemble the UNIX file system:

- `~/*` => `./src/*`: Resolves the `src` (home) directory
- `/*` => `./*`: Resolves the app (root) directory

Which would allow to import things like this:
```ts
import * from "~/components/Button/Button"
import * from "/src/components/Button/Button"
```

The `/` root alias would only be used for rare occasions when we need to import things outside of `src`.

**Comment by r0skar** [comment]
Some more thoughts:
- Dont create an alias for the project root folder. Files there are not supposed to be used in the app anyways. If you need something, import it from within `src`.
- That would leave us with only one alias, which means we could also just change the `baseUrl` to `./src`.
- However, we might want to get rid of `baseUrl` when updating Typescript to 4.1: https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#paths-without-baseurl

**Comment by edoardolunardi** [comment]
`baseUrl` or not, I would just use one, hence `~` 🙌

**Comment by r0skar** [comment]
This has been taken care of by 6f071aee73cd18363663608f70059f642af8a201. Path aliases have been reduced to one alias: `~/` -> `./src/`. Note that we still need to keep `baseUrl` around, because Next.Js needs to resolve path aliases.
