### ISSUE TITLE
Component naming convention

### ISSUE THREAD

**Issue by r0skar** [madebywild/wild-next#35]
A couple of thoughts:

Current approach: `components/ComponentName/ComponentName.tsx`
- Flexible and easily extendable
- A bit verbose

Alternative 1: `components/ComponentName.tsx`
- Straight forward
- Less flexible
- Can get messy with a lot of components

Alternative 2: `components/ComponentName/index.tsx`
- Similar to current approach
- Polutes codebase with "index" files (sucks when searching for files)

**Comment by edoardolunardi** [comment]
I honestly prefer the current one

**Comment by claudiopedrom** [comment]
To be honest I would prefer something like this:
`components/component-name/component-name.tsx` or `components/component-name/index.tsx`

Mostly because of this (@r0skar you are right now the better person to confirm 😄 ):
- https://stackoverflow.com/a/34671309

**Comment by r0skar** [comment]
While I didnt run into the mentioned issue yet, I can see how it could be a problem. Also readability is probably better - especially for `VeryLongAndComplicatedComponentNames`.

**Comment by edoardolunardi** [comment]
Never seen `a-very-long-react-component-written-like-this`. I would feel a bit uncomfortable 😂

**Comment by bs1180** [comment]
I like the current approach. You can also add a `package.json` to any folder, which allows importing the `/Component` version, but that's a bit OTT I think.

**Comment by r0skar** [comment]
This still needs some discussion, but the place for it going forward is https://docs.wild.plus/
