### ISSUE TITLE
Default export vs named export

### ISSUE THREAD

**Issue by r0skar** [madebywild/wild-next#36]
Discuss named vs default exports.

I suggest we stick to named exports whenever possible and only use default exports when necessary (iE a `next` page requires a default export).

**Comment by claudiopedrom** [comment]
I 100% agree with that.

**Comment by r0skar** [comment]
I have added a rule to our internal eslint config to make our life a bit easier: https://github.com/madebywild/eslint-config/commit/6b24795d7424c642cf34364de11b8b78c56e3d2e.
It will now display a warning when using default exports.
