### ISSUE TITLE
Tailwind - Custom spacing scale

### ISSUE THREAD

**Issue by r0skar** [madebywild/wild-next#37]
We have had issues in the past when the design is using spacings that are not part of the default TW spacing scale. This opens the question: keep TW spacing and force designers to stick to it or create a custom scale?

If creating a custom scale:
- Map it directly to a px value and increment by one? `spacing-10 => 10px; spacing-11 => 11px;`
Increase increments after a certain breakpoint? iE. map one spacing unit to one px until 100px and than increment by 10px.
- When using rems, do we want to change the base font size (to 62.5%), so that 1rem becomes 10px? This allows for much easier rem to px conversions.
Making that change, would require adapting the default text-size values as they are designed for `1rem=16px`.
- What about the relative spacing values? Should we create 0...100 units for 1 - 100%? `spacing-25/100 => 25%;`
- Same for viewport units?

**Comment by r0skar** [comment]
I went ahead and created a basic scale function and how it could be used:

```ts
const defaultTheme = require("tailwindcss/defaultTheme");

const pxToRem = (val) => val / 10;
const unitToVh = (val) => `${val}vh`;
const unitToVw = (val) => `${val}vw`;
const unitToRem = (val) => `${val}rem`;
const unitToPercent = (val) => `${val}%`;
const pxUnitToRem = (val) => unitToRem(pxToRem(val));

const createScale = ({ min = 0, max = 100, steps = 1, valFM, keyFM }) => {
  const limit = Math.round((max - min) / steps);
  const scale = [...new Array(limit + 1)].map((_, i) => min + i * steps);

  const sizes = scale.reduce((prev, curr) => {
    const key = keyFM ? keyFM(curr) : curr;
    const val = valFM && curr !== 0 ? valFM(curr) : curr;

    return { ...prev, [String(key)]: val };
  }, {});

  return sizes;
};

const tailwindConfig = {
  theme: {
    extend: {
      spacing: {
        // Spacing classes 0-100 in steps of 2px
        ...createScale({ steps: 2, valFM: pxUnitToRem }),
        // Spacing classes 110-500 in steps of 10px
        ...createScale({ min: 110, max: 500, steps: 10, valFM: pxUnitToRem }),
        // Spacing classes 600-2000 in steps of 100px
        ...createScale({ min: 600, max: 2000, steps: 100, valFM: pxUnitToRem }),
        // Spacing classes 1/100 - 100/100 in steps of 1%
        ...createScale({ valFM: unitToPercent, keyFM: (val) => `${val}/100` }),
        // Spacing classes 1vh - 100vh in steps of 1vh
        ...createScale({ valFM: unitToVh, keyFM: (val) => `${val}vh` }),
        // Spacing classes 1vh - 100vw in steps of 1vw
        ...createScale({ valFM: unitToVw, keyFM: (val) => `${val}vw` }),
      },
      inset: {
        // Inset classes 1/100 - 100/100 in steps of 1%
        ...createScale({ min: -100, valFM: unitToPercent, keyFM: (val) => `${val}/100` }),
      },
      opacity: {
        // Opacity classes 1 - 100 in steps of 0.1
        ...createScale({ valFM: (val) => `${val / 100}` }),
      },
    },
  },
};

module.exports = tailwindConfig;
```

**Comment by goellner** [comment]
just fyi we have a 8px grid in all our design systems. so the increments should be in steps of 8

**Comment by r0skar** [comment]
Hmm.. so maybe we want to stick to 2px until 128, then use increments of 8px? Something like this maybe:
- 0-128: 2px steps
- 128-256: 8px steps
- 256-512: 16px steps
- 512-1028: 32px steps

**Comment by goellner** [comment]
1px steps till 32 are what I have set up most of the time now

- 0-32: 1px steps
- 32-128: 2px steps
- 128-256: 8px steps
- 256-512: 16px steps
- 512-1028: 32px steps

**Comment by r0skar** [comment]
Not 100% sure about allowing 1px steps. Why not use 2px increments? If the designs really stick to their 8px grid, we should never run into a situation where we need an uneven amount of pixels. And if we still encounter some of these values in a design, we should probably just round them up?

**Comment by bs1180** [comment]
I don't think I'm a fan of overriding the tailwind spacing settings with different scales since:
- it ruins any chance of quick mental maths
- consistent increments (eg. 1px or 2px) going all the way up to 1028 or so just doesn't seem that useful to me

If the grid is already agreed at 8px, we should be pushing back at any design that deviates from it - a spacing of, say, 20px is more likely to be an error. Maybe there's a way to enforce it in Figma? 🤔

**Comment by r0skar** [comment]
I have added a Draft PR for the custom spacing scale https://github.com/madebywild/wild-next/pull/39.

While it actually should allow for quicker mental maths (because the classNames map to their px value), I agree with @bs1180 that using a linear scale from 0 up to 1024 feels a lot like using inline styles and we should seek to force designers to stick to their 8px scale.

**Comment by goellner** [comment]
the idea behind changing the default spacings was to avoid thinking about what 16px is on tailwinds spacing. when is see 16px in figma I want to use 1.6rem and don't have to think about it. when I see 20px i round up to 24px, so it becomes 2.4rem. the 1px steps up to 32px are for border radius for example. at least thats what I think it was used in one of my previous projects.

**Comment by r0skar** [comment]
The custom scale has [been merged](https://github.com/madebywild/wild-next/commit/ba063810802ec01dded64481779e039fa0f48f73).
