### ISSUE TITLE
Should we include next/image by default?

### ISSUE THREAD

**Issue by r0skar** [madebywild/wild-next#38]
https://nextjs.org/docs/api-reference/next/image

If so, does it make sense to also create a tiny styled-component wrapper around it?

**Comment by edoardolunardi** [comment]
What would be the benefit of using that? Does it add something more that we don't achieve use with `react-imgix` + a lazy lib?

**Comment by r0skar** [comment]
Yeah it basically is a lazy image component, but it enables all kind of image optimizations (even for remote images!). Its very similar to gatsby-image; you can read the docs for all features.

Its not so much a question if we want to use it (we do!), but if we also want to include it in the boilerplate? I guess it kinda makes sense, because I don't see us ever developing a website that doesn't need at least one image :thinking:

**Comment by edoardolunardi** [comment]
Yeah let's try it, I'm a bit curious. Tbh, I still have to find a very complete solution that combines really well image opt + lazy loading (in a reactish way) to the point that I was thinking of writing a npm package by myself. Let's see how much flexible this will be

**Comment by bs1180** [comment]
At the moment the new `next/image` component [doesn't work if you export a static site](https://github.com/vercel/next.js/issues/18356) - I had hoped it could help replace gatsby-image, but that's not possible, you still need the correct server side support. But if we're using next, using the image component seems worthwhile.

**Comment by r0skar** [comment]
We will not include it by default for now, but it is highly recommended we use it whenever it makes sense (iE if we dont need to create a static export or if we are using an external loader: https://github.com/vercel/next.js/blob/master/errors/export-image-api.md).

**Comment by r0skar** [comment]
Lets re-open this and see have things have changed in regards to static builds. Also check if the issue can be resolved by using an external loader (imgIX).

**Comment by r0skar** [comment]
Still not ready for primetime.
