### ISSUE TITLE
Tailwind defaults: what to extend and what to replace?

### ISSUE THREAD

**Issue by r0skar** [madebywild/wild-next#43]
At the moment, we are [extending the theme,](https://github.com/madebywild/wild-next/blob/2d6e2b5d2e0ede54d804f778d82f6e9025a1f076/tailwind.config.js#L7-L18) which means the default TW classes are still available. This makes sense for most of the config objects (like spacing, opacity etc.), but it might not be desirable for certain properties? Especially those related to the branding of a site: iE `font-size`, `font-family` and `color`.

By not extending these properties, we would be sure that only explicitly defined typography and colors (usually directly imported from Figma) are used.

**Comment by edoardolunardi** [comment]
@r0skar I've always replaced the ones you said (related to the branding) and sometimes the opacity (just to have the full scale). So I suggest to replace those
