### ISSUE TITLE
Permission to use excellent readme for twin documentation base

### ISSUE THREAD

**Issue by ben-rogerson** [madebywild/wild-next#46]
Hey there,

I just had a read of your README in this project and I'm very impressed!
I think you've done an amazing job of explaining the surface area of twin + styled-components. 👏👏👏 

I'd really like to improve the usage docs for twin and I'd love to use your readme as a base for this - it would really help out.

What do you think?

Also, I'm going to add a link to this repo on the twin + styled-components + next repo as I think people would love to use this.

Cheers,
Ben

**Comment by r0skar** [comment]
Hey @ben-rogerson - thanks for checking in and the kind words, but even more so for all the work on twin.macro. We really enjoy using it so far!

As for your question: feel free to use and link to whatever parts of the docs/project you want! Keep in mind that we are still in the process of fine-tuning the setup, so things will change. Probably starting with your `2.2.0` release :+1:

**Comment by ben-rogerson** [comment]
Thanks for permission to use your docs and it's great to hear your team is enjoying twin!

Can't wait to see how your template turns out 🔥🔥🔥 

Feel free to let me know if you've got any questions.
