### ISSUE TITLE
Craft CMS preview integration

### ISSUE THREAD

**Issue by edoardolunardi** [madebywild/wild-next#52]
Given that Craft CMS is our standard CMS - and we usually need to implement the preview in every project, should we include a basic implementation of it?

**Comment by r0skar** [comment]
I agree, but adding it should probably be part of a separate craft-wild-starter as it pulls in way too many deps for this boilerplate. Will close this for now, but lets keep in mind that we want to have a solid craft starter that includes API, preview, Auth etc.
